<template>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p><p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p><p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p><p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p><p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p><p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p><p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
  <p>我是switch组件</p>
</template>

<script lang="ts">

export default {
  name: 'Switch',
}
</script>